name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Enables manual triggering
    inputs:
      table_suffix:
        description: 'Table suffix for the ECR repository name'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production  # This environment will require approval
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get table suffix from stack.json or input
        id: stack-config
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.table_suffix }}" != "" ]]; then
            # Use manually provided table_suffix for workflow_dispatch
            echo "table_suffix=${{ github.event.inputs.table_suffix }}" >> $GITHUB_OUTPUT
            echo "Using manually provided table_suffix: ${{ github.event.inputs.table_suffix }}"
          else
            # Use table_suffix from stack.json for push or when input is not provided
            SUFFIX=$(jq -r '.table_suffix' stack.json)
            echo "table_suffix=$SUFFIX" >> $GITHUB_OUTPUT
            echo "Using table_suffix from stack.json: $SUFFIX"
          fi
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: flotorch-retriever-${{ steps.stack-config.outputs.table_suffix }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f fargate/handler/retriever/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
